# Generated by Django 4.2.7 on 2026-04-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('original_language', models.CharField(default='Русский', max_length=50, verbose_name='Язык оригинала')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('place_created', models.CharField(max_length=255, verbose_name='Место создания')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('doc_type', models.CharField(blank=True, max_length=100, verbose_name='Тип документа')),
                ('subjects', models.TextField(blank=True, verbose_name='Субъекты')),
                ('key_themes', models.TextField(blank=True, verbose_name='Ключевые темы')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Оригинал файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
