# Generated by Django 4.2.7 on 2026-04-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='document',
            name='discourse_type',
            field=models.CharField(blank=True, choices=[('programmatic', 'Программный'), ('normative', 'Нормативный'), ('declarative', 'Декларативный'), ('strategic', 'Стратегический'), ('operational', 'Операционный')], max_length=20, null=True, verbose_name='Политико-дискурсивный тип'),
        ),
        migrations.AddField(
            model_name='document',
            name='event_context',
            field=models.CharField(blank=True, help_text='Например: Саммит БРИКС 2023', max_length=500, verbose_name='Событие / обстоятельства создания'),
        ),
        migrations.AddField(
            model_name='document',
            name='has_translations',
            field=models.BooleanField(default=False, verbose_name='Наличие переводов'),
        ),
        migrations.AddField(
            model_name='document',
            name='related_documents',
            field=models.TextField(blank=True, help_text='Ссылки на предшествующие или последующие документы', null=True, verbose_name='Связанные документы'),
        ),
        migrations.AddField(
            model_name='document',
            name='translation_languages',
            field=models.CharField(blank=True, help_text='Например: русский, английский, китайский', max_length=200, null=True, verbose_name='Языки переводов'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateField(help_text='Формат: ГГГГ-ММ-ДД', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='full_text',
            field=models.TextField(verbose_name='Полный текст документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='genre',
            field=models.CharField(choices=[('declaration', 'Декларация'), ('communique', 'Коммюнике'), ('joint_statement', 'Совместное заявление'), ('protocol', 'Протокол'), ('charter', 'Хартия'), ('agreement', 'Соглашение'), ('treaty', 'Договор'), ('memorandum', 'Меморандум'), ('official_message', 'Официальное сообщение')], max_length=50, verbose_name='Жанр документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='key_themes',
            field=models.TextField(help_text='Теги через запятую: многополярность, регионализация, устойчивое развитие и др.', verbose_name='Ключевые темы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, help_text='Загрузите оригинальный файл документа', null=True, upload_to='documents/%Y/%m/', verbose_name='Оригинальный документ (PDF, DOC, TXT)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_language',
            field=models.CharField(choices=[('russian', 'Русский'), ('english', 'Английский'), ('chinese', 'Китайский'), ('french', 'Французский'), ('german', 'Немецкий'), ('spanish', 'Испанский'), ('arabic', 'Арабский')], default='russian', max_length=20, verbose_name='Язык оригинала'),
        ),
        migrations.AlterField(
            model_name='document',
            name='place_created',
            field=models.CharField(help_text='Город, страна', max_length=300, verbose_name='Место создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subjects',
            field=models.TextField(help_text='Список государств, лидеров, институтов через запятую', verbose_name='Субъекты (участники, акторы)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки в систему'),
        ),
    ]
