# Generated by Django 4.2.7 on 2026-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_remove_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='event_context',
            field=models.CharField(blank=True, help_text='Например: Саммит БРИКС 2023 (необязательно)', max_length=500, null=True, verbose_name='Событие / обстоятельства создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='Полный текст документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='genre',
            field=models.CharField(blank=True, choices=[('declaration', 'Декларация'), ('communique', 'Коммюнике'), ('joint_statement', 'Совместное заявление'), ('protocol', 'Протокол'), ('charter', 'Хартия'), ('agreement', 'Соглашение'), ('treaty', 'Договор'), ('memorandum', 'Меморандум'), ('official_message', 'Официальное сообщение')], max_length=50, null=True, verbose_name='Жанр документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='has_translations',
            field=models.BooleanField(blank=True, default=False, verbose_name='Наличие переводов'),
        ),
        migrations.AlterField(
            model_name='document',
            name='key_themes',
            field=models.TextField(blank=True, help_text='Теги через запятую (необязательно)', null=True, verbose_name='Ключевые темы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, help_text='Загрузите оригинальный файл (необязательно)', null=True, upload_to='documents/%Y/%m/', verbose_name='Оригинальный документ (PDF, DOC, TXT)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_language',
            field=models.CharField(blank=True, choices=[('russian', 'Русский'), ('english', 'Английский'), ('chinese', 'Китайский'), ('french', 'Французский'), ('german', 'Немецкий'), ('spanish', 'Испанский'), ('arabic', 'Арабский')], default='russian', max_length=20, null=True, verbose_name='Язык оригинала'),
        ),
        migrations.AlterField(
            model_name='document',
            name='place_created',
            field=models.CharField(blank=True, help_text='Город, страна (необязательно)', max_length=300, null=True, verbose_name='Место создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_documents',
            field=models.TextField(blank=True, help_text='Ссылки на предшествующие или последующие документы (необязательно)', null=True, verbose_name='Связанные документы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subjects',
            field=models.TextField(blank=True, help_text='Список государств, лидеров, институтов (необязательно)', null=True, verbose_name='Субъекты (участники, акторы)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='translation_languages',
            field=models.CharField(blank=True, help_text='Например: русский, английский, китайский (необязательно)', max_length=200, null=True, verbose_name='Языки переводов'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['genre'], name='documents_d_genre_e32145_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['original_language'], name='documents_d_origina_d50643_idx'),
        ),
    ]
