# Generated by Django 4.2.7 on 2026-04-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='translation_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/translations/%Y/%m/', verbose_name='Файл перевода (PDF, DOC, TXT)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='translation_languages',
            field=models.CharField(blank=True, choices=[('russian', 'Русский'), ('english', 'Английский'), ('chinese', 'Китайский'), ('french', 'Французский'), ('german', 'Немецкий'), ('spanish', 'Испанский'), ('arabic', 'Арабский')], max_length=20, null=True, verbose_name='Язык перевода'),
        ),
    ]
