# Generated by Django 4.2.7 on 2026-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_translation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='institution',
            field=models.CharField(blank=True, choices=[('sco', 'ШОС'), ('brics', 'БРИКС'), ('eas', 'ЕАС')], max_length=10, null=True, verbose_name='Институт'),
        ),
    ]
