# Generated by Django 4.2.7 on 2026-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='related_documents',
        ),
        migrations.AddField(
            model_name='document',
            name='related_documents',
            field=models.ManyToManyField(blank=True, to='documents.document', verbose_name='Связанные документы'),
        ),
    ]
